version: "3.3"
services:
  postgres:
    container_name: postgres
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: students_api
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql