/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package students.api;

import java.time.LocalDate;

import students.api.models.Student;

public class App {
    public static void main(String[] args) {
        final Student fulano = Student.of(1L, "fulano", LocalDate.now());
        System.out.println(fulano);
    }
}
